[keywords]
False = "假"
None = "空"
True = "真"
and = "并且"
as = "作为"
assert = "断言"
async = "异步"
await = "等待"
break = "跳出"
class = "类"
continue = "继续"
def = "定义"
del = "删除"
elif = "否则如果"
else = "否则"
except = "异常"
finally = "最后"
for = "对于"
from = "从"
global = "全局"
if = "如果"
import = "导入"
in = "在"
is = "是"
lambda = "匿名函数"
nonlocal = "非局部"
not = "非"
or = "或者"
pass = "通过"
raise = "抛出"
return = "返回"
try = "尝试"
while = "当"
with = "使用"
yield = "产出"